# Generated by Django 3.2.9 on 2021-11-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='page_limit',
            field=models.IntegerField(default=100),
        ),
    ]
