# Generated by Django 3.2.9 on 2021-12-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer_api', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pages_printed',
            field=models.IntegerField(default=0),
        ),
    ]
